# name: Deploy Itrust

# on:
#   push:
#     branches: [ main ]

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v4

#     - name: Setup PHP
#       uses: shivammathur/setup-php@v2
#       with:
#         php-version: '8.3'
#         extensions: mbstring, xml, zip, mysql, curl
#         coverage: none

#     - name: Install dependencies
#       run: |
#         composer install --no-interaction --no-dev --prefer-dist --optimize-autoloader

#     - name: Sync files to server
#       uses: appleboy/scp-action@v0.1.3
#       with:
#         host: ${{ secrets.SSH_HOST }}
#         username: 'root'
#         key: ${{ secrets.SSH_KEY }}
#         source: "./"
#         target: "/var/www/itrust-api/"
#         rm: true
#         strip_components: 1

#     - name: Run deployment commands
#       uses: appleboy/ssh-action@v0.1.8
#       with:
#         host: ${{ secrets.SSH_HOST }}
#         username: 'root'
#         key: ${{ secrets.SSH_KEY }}
#         script: |
#           cd /var/www/itrust-api
#           composer install --no-interaction --no-dev --prefer-dist --optimize-autoloader
#           php artisan migrate --force
#           php artisan cache:clear
#           php artisan view:clear
#           php artisan config:cache
#           chown -R root:root /var/www/itrust-api
#           chmod -R 775 storage
#           chmod -R 775 bootstrap/cache



name: Deploy to DigitalOcean

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.SSH_KEY }}

    - name: Verify SSH Connection
      run: |
        ssh -o StrictHostKeyChecking=no root@${{ secrets.SSH_HOST }} "echo 'SSH connection successful'"

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        extensions: mbstring, xml, zip, mysql, curl

    - name: Install dependencies
      run: |
        composer install --no-interaction --no-dev --prefer-dist --optimize-autoloader

    - name: Rsync files to server
      run: |
        rsync -avz -e "ssh -o StrictHostKeyChecking=no" \
          --exclude='.env' \
          --exclude='.git' \
          --exclude='storage' \
          --exclude='node_modules' \
          ./ root@${{ secrets.SSH_HOST }}:/var/www/itrust-api/

    - name: Run deployment commands
      run: |
        ssh -o StrictHostKeyChecking=no root@${{ secrets.SSH_HOST }} "
          cd /var/www/itrust-api
          composer install --no-interaction --no-dev --prefer-dist --optimize-autoloader
          php artisan migrate --force
          php artisan cache:clear
          php artisan view:clear
          php artisan config:cache
          chown -R root:root /var/www/itrust-api
          chmod -R 775 storage
          chmod -R 775 bootstrap/cache
        "